name: Push and publish to Docker Hub
on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{ github.repository }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker: ["single_cell", "graph_genome", "biotools", "hla", "assemble", "rna-seq"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files in the ${{ matrix.docker }} folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            ${{ matrix.docker }}/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build ${{ matrix.docker }}
        uses: docker/build-push-action@v2
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          context: ./${{ matrix.docker }}
          file: ./${{ matrix.docker }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME_BASE }}/${{ matrix.docker }}:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME_BASE }}/${{ matrix.docker }}:latest
